apiVersion: v1
kind: Service
metadata:
  name: federated-backend-us-east
  annotations:
    federation.tigera.io/serviceSelector: app == "backend-us-east"
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
  type: ClusterIP